name       : libreswan
version    : '4.6'
release    : 7
source     :
    - https://github.com/libreswan/libreswan/archive/refs/tags/v4.6.tar.gz : 26396f4826a682735772a4689a7ce9ae2d409d166a4b72836fc55d14bad356ff
homepage   : https://libreswan.org/
license    : GPL-2.0-or-later
component  : network.util
summary    : An Internet Key Exchange (IKE) implementation for Linux
description: |
    Libreswan is a free software implementation of the most widely supported and standarized VPN protocol based on ("IPsec") and the Internet Key Exchange ("IKE").
builddeps  :
    - pkgconfig(libcap-ng)
    - pkgconfig(libcurl)
    - pkgconfig(libldns)
    - pkgconfig(libselinux)
    - pkgconfig(libunbound)
    - pkgconfig(nss)
    - docbook-xml
    - xmlto
conflicts  :
    - strongswan
setup      : |
    %patch -p1 < $pkgfiles/pam_d_location.patch
build      : |
    %make PREFIX=/usr programs
install    : |
    %make_install PREFIX=/usr
