name       : libreswan
version    : 3.27
release    : 1
source     :
    - https://github.com/libreswan/libreswan/archive/v3.27.tar.gz : ead07dd701116094b483dc57e54e2a5ee9a06d3982bb142260bcbf3d1faf7b82
license    : GPL-2.0-or-later
component  : network.util
summary    : An Internet Key Exchange (IKE) implementation for Linux
description: |
    Libreswan is a free software implementation of the most widely supported and standarized VPN protocol based on ("IPsec") and the Internet Key Exchange ("IKE").
builddeps  :
    - pkgconfig(libcap-ng)
    - pkgconfig(libcurl)
    - pkgconfig(libldns)
    - pkgconfig(libselinux)
    - pkgconfig(libunbound)
    - pkgconfig(nss)
    - docbook-xml
    - xmlto
setup      : |
    %patch -p1 < $pkgfiles/pam_d_location.patch
build      : |
    %make INC_USRLOCAL=/usr programs
install    : |
    %make_install INC_USRLOCAL=/usr
