name       : libreswan
version    : 3.32
release    : 5
source     :
    - https://github.com/libreswan/libreswan/archive/v3.32.tar.gz : 236b57fee8f562302c54f2b16d8a839a9039fcb5893668e61b398ec6b179432e
license    : GPL-2.0-or-later
component  : network.util
summary    : An Internet Key Exchange (IKE) implementation for Linux
description: |
    Libreswan is a free software implementation of the most widely supported and standarized VPN protocol based on ("IPsec") and the Internet Key Exchange ("IKE").
builddeps  :
    - pkgconfig(libcap-ng)
    - pkgconfig(libcurl)
    - pkgconfig(libldns)
    - pkgconfig(libselinux)
    - pkgconfig(libunbound)
    - pkgconfig(nss)
    - docbook-xml
    - xmlto
conflicts  :
    - strongswan
setup      : |
    %patch -p1 < $pkgfiles/pam_d_location.patch
    %patch -p1 < $pkgfiles/fix-runtime-breakage-with-nss-3.52.patch
build      : |
    %make INC_USRLOCAL=/usr programs
install    : |
    %make_install INC_USRLOCAL=/usr
